import RoundContainer from 'components/RoundContainer'
import Head from 'next/head'
import RspImage from 'components/RspImage'
import { BiliIcon, WeixinIcon, MiniProgramIcon } from 'components/CustomIcon'
import style from './style.module.scss'

const data = [
	{
		text: '首页',
		link: '/',
	},
	{
		text: '归档',
		link: '/',
	},
	{
		text: '关于',
		link: '/',
	},
	{
		text: '搜索',
		link: '/',
	},
]

function Header({ title }: { title?: string }): JSX.Element {
	return (
		<RoundContainer className={style.header}>
			<Head>
				<title>{title}</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
				{/* remove it later */}
				<link
					rel="stylesheet"
					href="//at.alicdn.com/t/font_2754379_6spvjo7tqzq.css"
				/>
			</Head>
			<div className={style.info}>
				<RspImage containerClass={style.avatar} src="/images/me.png" alt="me" />
				<h1 className={style.name}>衫小小寨</h1>
				<p className={style.desc}>衫小寨的DEMO站</p>
				<div className={style.media}>
					<BiliIcon />
					<WeixinIcon />
					<MiniProgramIcon size={17} />
				</div>
			</div>

			<nav className={style.nav}>
				<div className={style.breadBtn}>==</div>
				<ul>
					{data.map((item, i) => (
						<li key={i}>{item.text}</li>
					))}
				</ul>
			</nav>
		</RoundContainer>
	)
}

export default Header
